const items =
  {
      integralmedica:[
      "INT CRISP BAR DOCE COCO C/12 V2",
      "INT COQUETELEIRA 1 DOSE NACIONAL",
      "INT AMINO BCAA 2:1:1 C/90 CAPS",
      "INT GALAO VERMELHO 1L",
      "INT THERMA PRO HARDCORE C/60",
      "INT DARK BAR P BUTTER AMENDOIM C/8 90G",
      "INT CRISP BAR TRUFA AVELA C/12 V2",
      "INT CRISP BAR ROMEU JULIETA C/12 V2",
      "INT IM GALAO ROSA 1L",
      "INT WHEY 100 PT PURE 900G MORANGO CONC",
      "INT WHEY ISO TRIPLE ZERO 907G CHOCOLATE",
      "INT WHEY ISO TRIPLE ZERO 907G MORANGO",
      "INT WHEY 100 PT PURE 900G BAUNILH CONC",
      "INT VO2 WHEY PROTEIN BAR CHOCOLATE C/12",
      "INT VO2 WHEY PROTEIN BAR COOKIES C/12",
      "INT CREATINA 300G INTEGRALMEDICA",
      "INT CARNIBOL CHOCOLATE 907 GR",
      "INT NUTRIWHEY PT 900G MORANGO V3",
      "INT NUTRIWHEY PT 900G CHOCOLATE V2",
      "INT GLUTAMINE NATURAL 300G",
      "INT CRISP BAR LEITE NINO/CREM AVELA C/12",
      "INT CREATINA HARDCORE 150G",
      "INT COQUETELEIRA 450ML INTEGRALMEDICA",
      "INT CARNIBOL SABOR SALTED CARAMEL 907 GR",
      "INT GLUTAMINE NATURAL 150G",
      "INT CRISP BAR DUO CRUNCH C/12",
      "INT MY WHEY PT 900G BAUNILHA"
  ]}
export default items;